version: '3.7'
services:
  di-geo-nginx:
    hostname: di-geo-nginx
    image: nginx:demo1
    container_name: di-geo-nginx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    ports:
      - 8888:8888
    environment:
      - TZ=Asia/Shanghai
#    deploy:
#      mode: replicated
#      replicas: 1
#      restart_policy:
#        condition: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web.conf:/etc/nginx/site-enabled/web.conf
      - ./GeoLiteCity.dat:/var/log/nginx/geoip/GeoLiteCity.dat
      - ./GeoIP.dat:/var/log/nginx/geoip/GeoIP.dat
    networks:
      - devops-compose

networks:
  devops-compose:
    external: true

