name: CI
# on:
#   push:
#     branches:
#       - master
#     tags:
#       - "*"
#   pull_request:

on: [push]

# Cancel in-progress runs in current workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sdk-generate:
    name: Generate SDKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: switch go version
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      # - name: Run golangci-lint
      #   uses: golangci/golangci-lint-action@v2
      #   env:
      #     GOGC: 100
      #   with:
      #     args: --timeout 10m0s
      #     version: v1.54.2
      #     skip-go-installation: true
      #     skip-pkg-cache: true
      - name: Build Kratos
        run: make install